name: Application Cron Job

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual trigger from GH Actions tab

jobs:
  publish_posts:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Publisher Endpoint
        run: |
          curl -i -X GET "https://social-media-manager-git-main-kosmishraai-5105s-projects.vercel.app/api/cron/publish" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
